# Generated by Django 3.2.14 on 2022-09-23 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('property_type', models.CharField(choices=[('Houses', 'Houses'), ('Office Spaces', 'Office Spaces'), ('Lands', 'Lands'), ('Semi Detached Bungalow', 'Semi Detached Bungalow'), ('Detached Bungalow', 'Detached Bungalow'), ('Semi Detached Duplex', 'Semi Detached Duplex'), ('Detached Duplex', 'Detached Duplex'), ('Co-working Space', 'Co Working Space'), ('Warehouse', 'Warehouse'), ('Shop in a mall', 'Shop In A Mall'), ('Self Contain', 'Self Contain'), ('Mini Flat', 'Mini Flats'), ('terraced bungalow', 'Terraced Bungalow'), ('terraced duplex', 'Terraced Duplex'), ('Commercial Properties', 'Commercial Properties')], default='Houses', max_length=50)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('open_house', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('lister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
